name: visualizer

on:
  workflow_dispatch: {}
  push:
    branches:
    - master

jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Repo Visualizer
      uses: githubocto/repo-visualizer@0.9.1
      with:
        output_file: "docs/diagram.svg"
        root_path: "xriweb/"
        excluded_paths: "dist,node_modules"
    - name: Update diagram
      id: make_diagram
      uses: githubocto/repo-visualizer@0.9.1
      with:
        output_file: "docs/utput-diagram.svg"
        artifact_name: "my-diagram"
    - name: Get artifact
      uses: actions/download-artifact@v4
      with:
        name: "my-diagram"
        path: "downloads"
